include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    invalid_annotation_target: ignore
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    prefer_single_quotes: true
    avoid_print: true
    always_use_package_imports: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    require_trailing_commas: true
    unnecessary_nullable_for_final_variable_declarations: true
